image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build-demo
    init: |
      cd pulsar-demo && mvn clean package install -Dmaven.test.skip=true

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false